import { Card } from './cardModal';

export const CARDS: Card[] = [
  { id: 1, name: 'Thor', url: './../assets/pics/thor.jpg' },
  { id: 2, name: 'IronMan', url: './../assets/pics/ironma.jpg' },
  { id: 3, name: 'Captain America', url: './../assets/pics/captain.jpg' },
  { id: 4, name: 'Rocket', url: './../assets/pics/rocket.jpg' },
  { id: 5, name: 'Hawkeye', url: './../assets/pics/hawkeye.jpg' },
  { id: 6, name: 'Hulk', url: './../assets/pics/hulk.jpg' },
  { id: 7, name: 'Spiderman', url: './../assets/pics/spiderman.jpg' },
  { id: 8, name: 'Docter Strange', url: './../assets/pics/strange.jpg' },
  { id: 9, name: 'Groot', url: './../assets/pics/groot.jpg' },
  { id: 10, name: 'Black Widow', url: './../assets/pics/blackwidow.jpg' },
  { id: 11, name: 'Okoye', url: './../assets/pics/okoye.jpg' },
  { id: 12, name: 'Shuri', url: './../assets/pics/shuri.jpg' },
  { id: 13, name: 'Black Panther', url: './../assets/pics/blackpanther.jpg' },
  { id: 14, name: 'Valkyrie', url: './../assets/pics/valkyrie.jpg' },
  { id: 15, name: 'Gamora', url: './../assets/pics/gamora.jpg' },
  { id: 16, name: 'Thor', url: './../assets/pics/thor.jpg' },
  { id: 17, name: 'IronMan', url: './../assets/pics/ironma.jpg' },
  { id: 18, name: 'Captain America', url: './../assets/pics/captain.jpg' },
  { id: 19, name: 'Rocket', url: './../assets/pics/rocket.jpg' },
  { id: 20, name: 'Hawkeye', url: './../assets/pics/hawkeye.jpg' },
  { id: 21, name: 'Hulk', url: './../assets/pics/hulk.jpg' },
  { id: 22, name: 'Spiderman', url: './../assets/pics/spiderman.jpg' },
  { id: 23, name: 'Docter Strange', url: './../assets/pics/strange.jpg' },
  { id: 24, name: 'Groot', url: './../assets/pics/groot.jpg' },
  { id: 25, name: 'Black Widow', url: './../assets/pics/blackwidow.jpg' },
  { id: 26, name: 'Okoye', url: './../assets/pics/okoye.jpg' },
  { id: 27, name: 'Shuri', url: './../assets/pics/shuri.jpg' },
  { id: 28, name: 'Black Panther', url: './../assets/pics/blackpanther.jpg' },
  { id: 29, name: 'Valkyrie', url: './../assets/pics/valkyrie.jpg' },
  { id: 30, name: 'Gamora', url: './../assets/pics/gamora.jpg' }
];
